# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Нравится'),
        ),
    ]
