# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170110_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Не нравится'),
        ),
    ]
